services:
  ai-app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8501:8501 # Streamlit default port
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      MODELS_URL: ${MODELS_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
